# Main Configuration for the Calculation Engine

schemas:
  positiveNumber:
    valueType: NUMBER
    min: 0
  percentage:
    valueType: NUMBER
    min: 0
    max: 1

dataElements:
  base_salary:
    type: required_input
    valueType: NUMBER
    isRequired: true
    schemaName: positiveNumber

  bonus_percentage:
    type: optional_input
    valueType: NUMBER
    isRequired: false
    schemaName: percentage
    rule:
        defaultExpression: 0
        

  calculated_bonus:
    type: intermediate
    valueType: NUMBER
    rule:
      defaultExpression: "base_salary * bonus_percentage"

  final_salary:
    type: output
    valueType: NUMBER
    rule:
      defaultExpression: "base_salary"
      scenarios:
        - condition: "bonus_percentage>0"
          expression: "base_salary + calculated_bonus"